=== netsi1964/json-schema-test/openweathermap.org.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://api.openweathermap.org",
  "type": "object",
  "properties": {
    "coord": {
      "id": "http://api.openweathermap.org/coord",
      "type": "object",
      "properties": {
        "lon": {
          "id": "http://api.openweathermap.org/coord/lon",
          "type": "number",
          "default": -0.13
        },
        "lat": {
          "id": "http://api.openweathermap.org/coord/lat",
          "type": "number",
          "default": 51.51
        }
      },
      "required": ["lon", "lat"]
    },
    "weather": {
      "id": "http://api.openweathermap.org/weather",
      "type": "array",
      "items": {
        "id": "http://api.openweathermap.org/weather/0",
        "type": "object",
        "properties": {
          "id": {
            "id": "http://api.openweathermap.org/weather/0/id",
            "type": "integer",
            "default": 802
          },
          "main": {
            "id": "http://api.openweathermap.org/weather/0/main",
            "type": "string",
            "default": "Clouds"
          },
          "description": {
            "id": "http://api.openweathermap.org/weather/0/description",
            "type": "string",
            "default": "scattered clouds"
          },
          "icon": {
            "id": "http://api.openweathermap.org/weather/0/icon",
            "type": "string",
            "default": "03d"
          }
        }
      }
    },
    "base": {
      "id": "http://api.openweathermap.org/base",
      "type": "string",
      "default": "cmc stations"
    },
    "main": {
      "id": "http://api.openweathermap.org/main",
      "type": "object",
      "properties": {
        "temp": {
          "id": "http://api.openweathermap.org/main/temp",
          "type": "number",
          "default": 284.4
        },
        "pressure": {
          "id": "http://api.openweathermap.org/main/pressure",
          "type": "integer",
          "default": 1020
        },
        "humidity": {
          "id": "http://api.openweathermap.org/main/humidity",
          "type": "integer",
          "default": 71
        },
        "temp_min": {
          "id": "http://api.openweathermap.org/main/temp_min",
          "type": "number",
          "default": 283.15
        },
        "temp_max": {
          "id": "http://api.openweathermap.org/main/temp_max",
          "type": "number",
          "default": 285.15
        }
      }
    },
    "wind": {
      "id": "http://api.openweathermap.org/wind",
      "type": "object",
      "properties": {
        "speed": {
          "id": "http://api.openweathermap.org/wind/speed",
          "type": "number",
          "default": 10.8
        },
        "deg": {
          "id": "http://api.openweathermap.org/wind/deg",
          "type": "integer",
          "default": 220
        },
        "gust": {
          "id": "http://api.openweathermap.org/wind/gust",
          "type": "number",
          "default": 15.9
        }
      }
    },
    "clouds": {
      "id": "http://api.openweathermap.org/clouds",
      "type": "object",
      "properties": {
        "all": {
          "id": "http://api.openweathermap.org/clouds/all",
          "type": "integer",
          "default": 40
        }
      }
    },
    "dt": {
      "id": "http://api.openweathermap.org/dt",
      "type": "integer",
      "default": 1449303600
    },
    "sys": {
      "id": "http://api.openweathermap.org/sys",
      "type": "object",
      "properties": {
        "type": {
          "id": "http://api.openweathermap.org/sys/type",
          "type": "integer",
          "default": 1
        },
        "id": {
          "id": "http://api.openweathermap.org/sys/id",
          "type": "integer",
          "default": 5093
        },
        "message": {
          "id": "http://api.openweathermap.org/sys/message",
          "type": "number",
          "default": 0.0081
        },
        "country": {
          "id": "http://api.openweathermap.org/sys/country",
          "type": "string",
          "default": "GB"
        },
        "sunrise": {
          "id": "http://api.openweathermap.org/sys/sunrise",
          "type": "integer",
          "default": 1449301749
        },
        "sunset": {
          "id": "http://api.openweathermap.org/sys/sunset",
          "type": "integer",
          "default": 1449330774
        }
      }
    },
    "id": {
      "id": "http://api.openweathermap.org/id",
      "type": "integer",
      "default": 2643743
    },
    "name": {
      "id": "http://api.openweathermap.org/name",
      "type": "string",
      "default": "London"
    },
    "cod": {
      "id": "http://api.openweathermap.org/cod",
      "type": "integer",
      "default": 200
    }
  },
  "required": ["coord", "weather", "base", "main", "wind", "clouds", "dt", "sys", "id", "name", "cod"]
}

=== netsi1964/json-schema-test/rawJSON.json
{
  "coord": {
    "lon": -0.13,
    "lat": 51.51
  },
  "weather": [{
    "id": 802,
    "main": "Clouds",
    "description": "scattered clouds",
    "icon": "03d"
  }],
  "base": "cmc stations",
  "main": {
    "temp": 284.4,
    "pressure": 1020,
    "humidity": 71,
    "temp_min": 283.15,
    "temp_max": 285.15
  },
  "wind": {
    "speed": 10.8,
    "deg": 220,
    "gust": 15.9
  },
  "clouds": {
    "all": 40
  },
  "dt": 1449303600,
  "sys": {
    "type": 1,
    "id": 5093,
    "message": 0.0081,
    "country": "GB",
    "sunrise": 1449301749,
    "sunset": 1449330774
  },
  "id": 2643743,
  "name": "London",
  "cod": 200
}
